// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_win11_dev_label = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_win11_dev_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_win11_dev_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_win11_dev_label, -6);
    lv_obj_set_y(ui_win11_dev_label, -32);
    lv_obj_set_align(ui_win11_dev_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_win11_dev_label, "Win11 Dev");
    lv_obj_set_style_text_font(ui_win11_dev_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_win11_start_button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_win11_start_button, 80);
    lv_obj_set_height(ui_win11_start_button, 40);
    lv_obj_set_x(ui_win11_start_button, -45);
    lv_obj_set_y(ui_win11_start_button, 28);
    lv_obj_set_align(ui_win11_start_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_win11_start_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_win11_start_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_win11_start_button, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_win11_start_button, lv_color_hex(0x31E800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_win11_start_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_win11_stop_button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_win11_stop_button, 80);
    lv_obj_set_height(ui_win11_stop_button, 40);
    lv_obj_set_x(ui_win11_stop_button, 45);
    lv_obj_set_y(ui_win11_stop_button, 26);
    lv_obj_set_align(ui_win11_stop_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_win11_stop_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_win11_stop_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_win11_stop_button, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_win11_stop_button, lv_color_hex(0xE80038), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_win11_stop_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_win11_start_button, ui_event_win11_start_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_win11_stop_button, ui_event_win11_stop_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
