// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brightness_option = lv_checkbox_create(ui_Screen3);
    lv_checkbox_set_text(ui_brightness_option, "Brightness Option");
    lv_obj_set_width(ui_brightness_option, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightness_option, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brightness_option, 0);
    lv_obj_set_y(ui_brightness_option, -25);
    lv_obj_set_align(ui_brightness_option, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brightness_option, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_brightness_slider = lv_slider_create(ui_Screen3);
    lv_slider_set_value(ui_brightness_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_brightness_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_brightness_slider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_brightness_slider, 150);
    lv_obj_set_height(ui_brightness_slider, 10);
    lv_obj_set_x(ui_brightness_slider, 3);
    lv_obj_set_y(ui_brightness_slider, 40);
    lv_obj_set_align(ui_brightness_slider, LV_ALIGN_CENTER);


    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
