// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_connect_button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_connect_button, 80);
    lv_obj_set_height(ui_connect_button, 80);
    lv_obj_set_x(ui_connect_button, 0);
    lv_obj_set_y(ui_connect_button, -40);
    lv_obj_set_align(ui_connect_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connect_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connect_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connect_button, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connect_button, lv_color_hex(0xE8D500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connect_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_connect_button, &ui_img_connect_small_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_os_select_dropdown = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_os_select_dropdown, "Win11 Dev\nWin10 Game\nZorin OS");
    lv_obj_set_width(ui_os_select_dropdown, 150);
    lv_obj_set_height(ui_os_select_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_os_select_dropdown, 0);
    lv_obj_set_y(ui_os_select_dropdown, 30);
    lv_obj_set_align(ui_os_select_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_os_select_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_command_dropdown = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_command_dropdown, "Start\nStop");
    lv_obj_set_width(ui_command_dropdown, 150);
    lv_obj_set_height(ui_command_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_command_dropdown, 0);
    lv_obj_set_y(ui_command_dropdown, 70);
    lv_obj_set_align(ui_command_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_command_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_status_spiner = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_status_spiner, 80);
    lv_obj_set_height(ui_status_spiner, 80);
    lv_obj_set_x(ui_status_spiner, 0);
    lv_obj_set_y(ui_status_spiner, -25);
    lv_obj_set_align(ui_status_spiner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_status_spiner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_status_spiner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_status_label = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_status_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_status_label, 0);
    lv_obj_set_y(ui_status_label, 45);
    lv_obj_set_align(ui_status_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status_label, "Connecting");
    lv_obj_add_flag(ui_status_label, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_connect_button, ui_event_connect_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
