// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_accelerometer_en_sw(lv_event_t * e);
extern lv_obj_t * ui_accelerometer_en_sw;
extern lv_obj_t * ui_x_display_bar;
extern lv_obj_t * ui_y_display_bar;
extern lv_obj_t * ui_z_display_bar;
extern lv_obj_t * ui_x_label;
extern lv_obj_t * ui_y_label;
extern lv_obj_t * ui_z_label;
extern lv_obj_t * ui_on_label;
extern lv_obj_t * ui_off_label;
extern lv_obj_t * ui_title;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
